version: 2
jobs:
  build:ß
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test