version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
  cypress: cypress-io/cypress@1
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
              - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn size
      - run: yarn test
      - run: npx cypress install
      - run: yarn ci:cypress-run
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: high
      - run: yarn build
      - aws-s3/sync:
          from: build
          to: 's3://react-demo-test/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true